package org.example.model;

import jakarta.persistence.*;
import lombok.Data;

import java.util.Objects;

@Data
@Entity
@Table(name = "todo")
public class Todo {


    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String task;

    public Todo() {

    }

    public Todo(String task) {
        this.task = task;
    }

    // --- Equals, HashCode, and ToString (Generated by IDE) ---

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Todo todo = (Todo) o;
        return Objects.equals(id, todo.id) &&
                Objects.equals(task, todo.task);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, task);
    }

    @Override
    public String toString() {
        return "Todo{" +
                "id=" + id +
                ", task='" + task + '\'' +
                '}';
    }
}